### ISSUE TITLE
Middleware not cleaning up ActiveRecord connection causes leak and connection timeout

### ISSUE THREAD

**Issue by typeoneerror** [influitive/apartment-sidekiq#11]
More a question than a bug, but I'm curious if this gem has been tested with Sidekiq 4 yet? I bumped to 4 to see if it would work without issue, but unfortunately, I'm running into some issues. I'm wondering it might be related to the apartment-sidekiq gem (I can see it in the backtrace, but I think it might be just the trace, not actually originating from apartment-sidekiq) or if you might be able to say whether it's related to Sidekiq.

I posted a bug on Sidekiq's issues here: https://github.com/mperham/sidekiq/issues/2769. The stack trace is in that bug.

**Comment by bradrobertson** [comment]
Haven't tested w/ Sidekiq 4.0 yet. Would love to hear your findings.

**Comment by typeoneerror** [comment]
I've actually found that I get the same error with 3.x if a few jobs are being processed. I rolled back to 0.2.0 and the issue *appears* to be gone now. I think that https://github.com/influitive/apartment-sidekiq/commit/c233dfeae51f8cb370a2b36d8fa96bc3c0b96817 has effected ActiveRecord's connection situation (not cleaning up? I donno, it's a bit beyond my pay grade). In any case, that commit looks to be the issue, and potentially related to https://github.com/influitive/apartment-sidekiq/issues/9.

**Comment by rdunlop** [comment]
I have also bumped into this same thing. Upgrading `apartment-sidekiq` to 1.0.0 (with sidekiq `4.0.2`) I get the ActiveRecord::ConnectionTimeoutError on my 5th sidekiq thread (all of which do ActiveRecord actions). (I watched the logs, and counted the number of different "TID-owk4ld2v8" entries...and it was always on the 5th different one that this happens).

Downgrading back to 0.2.0 and the problem does not appear, using a 100% reproduction scenario. I'm going to attempt to investigate further no.w

**Comment by rdunlop** [comment]
Here's what I _think_ I've learned.

I think that https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L122 indicates that the middleware chain is as follows:
```
  Sidekiq::Middleware::Server::Logging
  Sidekiq::Middleware::Server::RetryJobs
  Sidekiq::Middleware::Server::ActiveRecord
```

The `ActiveRecord` part is the key to this problem, in that it invokes the `::ActiveRecord::Base.clear_active_connections!` method, which releases any used ActiveRecord connections during the execution. (https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/active_record.rb#L8)

It is my theory that because we are now inserting the middleware at a level **before** the sidekiq ActiveRecord middleware, we may incorrectly end up loading ActiveRecord, and losing the connection.

Details:
and, the old code (https://github.com/influitive/apartment-sidekiq/pull/7/files#diff-6bfe71488bd0566b6a2f3d1e0f42fa3fL23) 
used to do:
```chain.add Apartment::Sidekiq::Middleware::Server```
(which I think would mean that the Apartment::Sidekiq::Middleware::Server would be wrapped within the Sidekiq::ActiveRecord middleware block)

and the new code now does
```
chain.insert_before ::Sidekiq::Middleware::Server::RetryJobs, Apartment::Sidekiq::Middleware::Server
```
(which I think means that it is no longer wrapped in the Sidekiq::ActiveRecord middleware block).

I look forward to learning whether my understanding is correct.

**Comment by Frank004** [comment]
@typeoneerror  what ver of sidekiq and apartment-sidekiq your running without this error

**Comment by typeoneerror** [comment]
@Frank004 3.x branch of sidekiq and 0.2 apartment-sidekiq. 

@rdunlop yep, this is was my understanding of the issue as well. I did talk to Mike P from Sidekiq last week and he thinks that apartment-sidekiq may need to manage/clean-up the active record connection instead if it needs to be inserted in the middleware chain earlier (https://github.com/influitive/apartment-sidekiq/issues/9#issuecomment-173652430)

**Comment by Frank004** [comment]
@typeoneerror mmm... im getting the same error for some reason. :/ ill keep looking for a workaround for the moment.

**Comment by brandonparsons** [comment]
FWIW I'm also seeing this error.

`apartment-sidekiq`: 1.0.0
`sidekiq`: 4.0.2

It appears to have gone away when I downgraded Sidekiq to 3.5.4.

**Comment by Frank004** [comment]
@brandonparsons can you post ur gemfile for the apartment-sidekiq and sidekiq. As all the one I put get the same error. :/

**Comment by brandonparsons** [comment]
Hi @Frank004 - all I did was the following:

```
gem "sidekiq", '3.5.4'
gem "apartment"
gem "apartment-sidekiq"
```

Nothing special - just downgraded `sidekiq` and left `apartment-sidekiq` at 1.0. I'm just getting this project up and running though - the worker is not under a lot of load. It's possible the error might come back for me later, but for the time being it has gone away.

**Comment by brandonparsons** [comment]
Maybe it doesn't work. I'm not sure. I'm considering dropping `apartment-sidekiq` back to 0.2.0.

**Comment by typeoneerror** [comment]
@brandonparsons 1.0.0 doesn't work with 3.x or 4.x. we've dropped back to 0.2.0. been considering just dropping the gem entirely and explicitly enqueuing jobs with tenant names. I wish I knew how to fix this gem!

**Comment by Frank004** [comment]
Yes I may create a job and look on how to pass the tenant

**Comment by brandonparsons** [comment]
Thanks for the heads up @typeoneerror .  I'm not that far into my project, so I may do just that (explicitly set tenant in every job and activate within the job).

I'm a "side programmer", so very unlikely I'll be able to sort anything else. Please hit me up if you do figure something out!!

**Comment by Frank004** [comment]
@brandonparsons can you give me a tips on how to pass the tenant in a job

**Comment by typeoneerror** [comment]
@Frank004 @bradrobertson 

`MyJob.perform_later(Apartment::Tenant.current, other, param)`

And then in the job, you'd want to switch into the tenant...\
```
def perform(tenant_name, other, param)
  Apartment::Tenant.switch(tenant_name) do

  end
end
```

This is effectively what this gem does, it just passes `.current` as an "extra" param to the job when scheduled.

**Comment by Frank004** [comment]
@typeoneerror  Thank you.

**Comment by wynksaiddestroy** [comment]
I'm experiencing this issue, too. Downgrading to 0.2.0 solved the problem for the moment. Is there any chance on getting this fixed? If someone needs any logs or stack traces just leave a comment and I'll try to provide any information neccesary. Thanks in advance.

**Comment by Frank004** [comment]
@typeoneerror I try a manual task just for test and pass the apartment like this and still get the error

```
class MyWorker
  include Sidekiq::Worker
  def perform(subdomain, name, number)
    Apartment::Tenant.switch!(subdomain) do
      #do something
    end
  end
end
![screen shot 2016-06-07 at 10 00 42 am](https://cloud.githubusercontent.com/assets/7242689/15860362/bcf8f3ba-2c96-11e6-9582-b8b39eafc780.jpg)

```

**Comment by Frank004** [comment]
This what the guys at sidekiq comment on my issue post.
https://github.com/mperham/sidekiq/issues/3005

**Comment by typeoneerror** [comment]
Uh huh, we've discussed this before. The middleware should be added at the end of the chain, as it was in 0.2. This is the commit that causes the issue: https://github.com/influitive/apartment-sidekiq/commit/cdc7429c5628cb2c265f30ff6845503077ceaa90

I'm not sure the "retries" issue that the commit is fixing is actually an issue, but I think I might understand what the solution may be. In order to insert before the activerecord middleware, I think we may have to manage the activerecord connection pool ourselves here. I found this interesting lil guy that might help:

https://gist.github.com/thbar/b3795c4dd1dd5c46f919

Compare to the original: https://github.com/mperham/sidekiq/blob/3_x/lib/sidekiq/middleware/server/active_record.rb#L5

When I talked creator of sidekiq, he implied that Apartment-Sidekiq would need to manage the pool itself, so this seems like an intersting path.

Thoughts?

**Comment by typeoneerror** [comment]
@andrba, @bradrobertson, what do you think about the following. I know that @andrba's 1.0 commit isn't working for cleaning up those connections, so I'm wondering if we don't clean those up _in_ the Apartment::Sidekiq middleware _before_ the RetryJobs. 

My thinking is that the job is run in the Apartment middleware which opens up connections which are potentially never closed because they are not being called in context of the `yield` of that ActiveRecord middleware.

```rb
config.server_middleware do |chain|
  chain.remove ::Sidekiq::Middleware::Server::ActiveRecord
  chain.insert_before ::Sidekiq::Middleware::Server::RetryJobs, Apartment::Sidekiq::Middleware::Server
end
```

```rb
module Apartment::Sidekiq::Middleware
  class Server
    def call(worker_class, item, queue)
      Apartment::Tenant.switch(item['apartment']) do
        yield
      end
    ensure
      ::ActiveRecord::Base.clear_active_connections!
    end
  end
end
```

Middleware stack would look like:

1. Sidekiq::Middleware::Server::Logging
2. Apartment::Sidekiq::Middleware::Server
3. Sidekiq::Middleware::Server::RetryJobs

Still, I don't know if cleaning up the connection pool _prior_ to pushing retries will work. From the looks of it, retries just accesses redis, so we don't really need activerecord there? I donno, I'm just guessing here.

**Comment by typeoneerror** [comment]
I drew this out on paper just to have an idea how middleware is working:

**with `add` (0.2)**

```rb
Logger do
  RetryJobs do
    ActiveRecord do
      Apartment      
      # our logic here  <-- connections opened
    ensure
      # cleanup!          <-- connections closed
    end
  end
end
```

**with `insert_before` (1.0.0)**

```rb
Logger do
  Apartment do          <-- connections opened
    # our logic here
    RetryJobs do        <-- Apartment is not wrapped by Retry so are they even caught?
      ActiveRecord do
        # nothing?    
      ensure
        # cleanup!      <-- what are we cleaning up here?
      end
    end
  end                   <-- connections still open?
end

To me, it seems that because the Apartment middleware is not wrapped by ActiveRecord that any "connections it opens" are not closed.

**Comment by typeoneerror** [comment]
Locally, I set up a TestJob to raise an error:

```rb
class TestJob < ActiveJob::Base
  def perform
    puts "Performed test job at #{Time.current} with schema #{Apartment::Tenant.current}"
    raise StandardError, 'Hey this did not work'
  end
end
```

In console I ran:

```rb
Apartment::Tenant.switch!('oki')
TestJob.perform_later
```

```
=> [TestJob:oki:08 Jun 11:43] Performed test job at 2016-06-08 11:43:26 -0700 with schema oki
```

The job fails and is in the retry queue:

```
{"created_at"=>1465411305.1716852, "apartment"=>"oki"}
```

Here are the retry logs:

```
=> [TestJob:oki:08 Jun 11:42] Performed test job at 2016-06-08 11:42:24 -0700 with schema oki
=> [TestJob:oki:08 Jun 11:43] Performed test job at 2016-06-08 11:43:06 -0700 with schema oki
=> [TestJob:oki:08 Jun 11:43] Performed test job at 2016-06-08 11:43:21 -0700 with schema oki
=> [TestJob:oki:08 Jun 11:43] Performed test job at 2016-06-08 11:43:26 -0700 with schema oki
=> [TestJob:oki:08 Jun 11:43] Performed test job at 2016-06-08 11:43:53 -0700 with schema oki
=> [TestJob:oki:08 Jun 11:45] Performed test job at 2016-06-08 11:45:13 -0700 with schema oki
```

So you can see the apartment is still there on retries. So, @andrba, can you explain your retries commit? Why that wasn't working for you? 

@bradrobertson, what do you think about rolling back those commits, releasing 2.0.0 and pulling 1.0.0 from rubygems? Would be happy to submit that PR if we can all confirm that the retries system is working fine with 0.2. I am not seeing the same issue as @andrba, but I could be wrong.

**Comment by bradrobertson** [comment]
I'm happy to roll it back. I didn't fully understand why it was needed in the first place. @andrba can you comment?

**Comment by rposborne** [comment]
@typeoneerror I actually had 1.0.0 losing jobs when hitting the connection bug, which would contradict the change in the retry system. Can anyone else confirm job loss on `apartment 1.02` and `apartment-sidekiq 1.0` with `sidekiq 4.1.2`

**Comment by typeoneerror** [comment]
@rposborne that would make sense if the error was being thrown in the Apartment middleware. Using the pseudocode for 1.0.0 I wrote above, that error would never be captured by RetryJobs so I think in this case, it'd just go into Sidekiq's "fail" queue.

**Comment by rposborne** [comment]
@typeoneerror that is exactly what we were seeing. 

@bradrobertson, with jobs being lost, it might not be a bad idea to yank as is ☹️

**Comment by typeoneerror** [comment]
Opened a PR for 1.1.0 with a rollback. Probably not best to merge and release until we get a few more confirmations on this, but yanking 1.0 is probably a good idea.

**Comment by bradrobertson** [comment]
ok release 1.1. Thanks guys! We'll hold off on yank'ng for now

**Comment by typeoneerror** [comment]
@bradrobertson cool, thanks. If I understand the issue correctly, I think this should resolve #9 #10 #11.

**Comment by mperham** [comment]
Good detective work.  You should never put any "unsafe" middleware before RetryJobs.  RetryJobs should wrap **everything** that could raise an exception so it can push the errored job back to Redis for retry later.  Sidekiq Pro's reliable fetch is the only 100% solution to job loss.  This is one edge case that shows why.

**Comment by bradrobertson** [comment]
Ya makes sense, thanks @mperham

**Comment by andrba** [comment]
@typeoneerror @bradrobertson the intention was to have a correct tenant in the `sidekiq_retries_exhausted` block. So instead of switching it manually inside this block like below

```ruby
sidekiq_retries_exhausted do |msg|
  ::Apartment::Tenant.switch(msg['apartment']) do
    #... your code ...
  end
end
```
it would be done by the gem.

**Comment by mperham** [comment]
@andrba the intention cannot be done safely.  You need to explicitly switch and cleanup any connections.  I hate that callback and wish I'd never implemented it.
