### ISSUE TITLE
Release for changes from Apartment::Tenant#process to Apartment::Tenant#switch

### ISSUE THREAD

**Issue by dukz** [influitive/apartment-sidekiq#4]
Took me an hour to figure this one out because I was looking at code inside github instead of the code in my gems folder.

Any plans on getting this pushed out soon?

Thanks.

**Comment by bradrobertson** [comment]
Will be releasing a 1.0 soon with the new interface. Just been a bit busy. I'd say a few weeks maybe?

**Comment by dukz** [comment]
OK. Thanks. In the meantime, I'll just use the github refs for my Gemfile. :) Thanks.

**Comment by alepore** [comment]
@bradrobertson please remember the release when you have time :heart: :heart:

**Comment by bradrobertson** [comment]
gah, sorry! will do right now

**Comment by bradrobertson** [comment]
released! Only 1 year too late :p   Sorry all.
