### ISSUE TITLE
ConnectionBad: Connection is Closed when running concurrent sidekiq threads

### ISSUE THREAD

**Issue by kmewhort** [influitive/apartment-sidekiq#8]
When running jobs that are firing multiple threads at a time, we keep getting: `PG:ConnectionBad  Connection is Closed`.  

This occurs in Apartment's `current` call (apartment-1.0.2/lib/apartment/adapters/abstract_adapter.rb:53), fired from `previous_tenant = current` in the `switch` call.

I wonder if this is perhaps related to the fact that sidekiq closes all active connections after each job: `sidekiq-3.5.0/lib/sidekiq/middleware/server/active_record.rb:6`, and then there's no connections left to for the Apartment call to check the current database...

  `

**Comment by bradrobertson** [comment]
Sorry, you're saying the jobs themselves are creating `new` threads? Or just the fact that sidekiq uses threads is causing issues? We use `apartment-sidekiq` with no issues whatsoever, but we don't have our jobs spin up *new* threads at all.

**Comment by bradrobertson** [comment]
Fixed #11
