### ISSUE TITLE
If a job throws an exception, the connection is leaked from the connection pool

### ISSUE THREAD

**Issue by sainejob** [influitive/apartment-sidekiq#9]
Here's my scenario:

- 1 unicorn worker
- 1 sidekiq worker
- mysql2 connection pool set to 2

Then I run a sidekiq job which throws NPE.  

The middleware chain is executed, `Sidekiq::Middleware::Server::ActiveRecord` runs `::ActiveRecord::Base.clear_active_connections!`, then `Apartment::Sidekiq::Middleware::Server` tried to `switch` 

Then another exception is thrown `ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)` because there is no connection for apartment to reset and I also see there are 3 connections now instead of 2.  The third cannot be reaped and is a zombie thread just sleeping from what I can tell.  

I've found that if I simply re-order the middleware chain like so: 

```
# line 24 of /lib/apartment/sidekiq.rb
chain.insert_after ::Sidekiq::Middleware::Server::ActiveRecord, Apartment::Sidekiq::Middleware::Server
```
Then the exception throws and we `switch!` before `Sidekiq::Middleware::Server::ActiveRecord` has cleaned up.

Is there a particular reason for the current ordering?

**Comment by bradrobertson** [comment]
@andrba can you comment? It's your change.

**Comment by andrba** [comment]
@sainejob the reason for that PR was the fact that `sidekiq_retries_exhausted` ignored tenants and used the public schema. If that change it's causing issues we can think of other methods to ensure that the retries_exhausted handler uses the correct tenant.

**Comment by typeoneerror** [comment]
FYI, I talked to Mike at Sidekiq during a consulting session and showed him the issues here. They all seem to be related:

https://github.com/influitive/apartment-sidekiq/issues/8
https://github.com/influitive/apartment-sidekiq/issues/9
https://github.com/influitive/apartment-sidekiq/issues/11

The only advice he could give off the top of his head is that you may have to clean up the active record connection yourself. My thinking is that you'd `pop` off the activerecord middleware from the stack, append the apartment-sidekiq middleware and then clean up the active record connection yourself after the switch. I'm not sure if something like that would fix the `sidekiq_retries_exhausted` situation.

**Comment by bradrobertson** [comment]
Should be fixed now, re-open if we see any other issues.
